import { RoleType } from '@/api/user';

export type PermissionEvents =
  'READ_HANDOVER'
  | 'EDIT_COACH_OPERATION_TARGET'
  | 'VIEW_USER_SETTING'
  | 'VIEW_GOOGLE_REVIEW'
  | 'EDIT_GOOGLE_REVIEW'
  | 'READ_EDUCATION_REVIEW'
  | 'EDIT_EDUCATION_REVIEW'
  | 'READ_PT_LEVEL'
  | 'EDIT_PT_LEVEL'
  | 'EDIT_HIRE_TIME'
  | 'VIEW_POINTS_BONUS'
  | 'VIEW_RELOCATE_BONUS'
  | 'EDIT_RELOCATE_BONUS';
type CanDo = Partial<{ readonly [key in PermissionEvents]: boolean }>;

export const RolePermissions: { [role in RoleType]: CanDo } = {
  [RoleType['系統管理者']]: {
    READ_HANDOVER: true,
    EDIT_COACH_OPERATION_TARGET: false,
    VIEW_USER_SETTING: true,
    VIEW_GOOGLE_REVIEW: true,
    EDIT_GOOGLE_REVIEW: true,
    READ_EDUCATION_REVIEW: true,
    EDIT_EDUCATION_REVIEW: true,
    EDIT_PT_LEVEL: true,
    READ_PT_LEVEL: true,
    EDIT_HIRE_TIME: true,
    VIEW_POINTS_BONUS: true,
    VIEW_RELOCATE_BONUS: true,
    EDIT_RELOCATE_BONUS: true,
  },
  [RoleType['院長']]: {
    READ_HANDOVER: true,
    EDIT_COACH_OPERATION_TARGET: false,
    VIEW_USER_SETTING: true,
    VIEW_GOOGLE_REVIEW: true,
    EDIT_GOOGLE_REVIEW: true,
    READ_EDUCATION_REVIEW: true,
    EDIT_EDUCATION_REVIEW: true,
    EDIT_PT_LEVEL: true,
    READ_PT_LEVEL: true,
    EDIT_HIRE_TIME: true,
    VIEW_POINTS_BONUS: true,
    VIEW_RELOCATE_BONUS: true,
    EDIT_RELOCATE_BONUS: true,
  },
  [RoleType['副院長']]: {
    READ_HANDOVER: true,
    EDIT_COACH_OPERATION_TARGET: false,
    VIEW_USER_SETTING: true,
    VIEW_GOOGLE_REVIEW: true,
    EDIT_GOOGLE_REVIEW: true,
    READ_EDUCATION_REVIEW: true,
    EDIT_EDUCATION_REVIEW: true,
    EDIT_PT_LEVEL: true,
    READ_PT_LEVEL: true,
    EDIT_HIRE_TIME: true,
    VIEW_POINTS_BONUS: true,
    VIEW_RELOCATE_BONUS: true,
    EDIT_RELOCATE_BONUS: true,
  },
  [RoleType['店長']]: {
    READ_HANDOVER: true,
    EDIT_COACH_OPERATION_TARGET: true,
    VIEW_USER_SETTING: false,
    VIEW_GOOGLE_REVIEW: false,
    EDIT_GOOGLE_REVIEW: false,
    READ_EDUCATION_REVIEW: false,
    EDIT_EDUCATION_REVIEW: false,
    EDIT_PT_LEVEL: false,
    READ_PT_LEVEL: false,
    EDIT_HIRE_TIME: false,
    VIEW_POINTS_BONUS: false,
    VIEW_RELOCATE_BONUS: false,
    EDIT_RELOCATE_BONUS: false,
  },
  [RoleType['副店長']]: {
    READ_HANDOVER: true,
    EDIT_COACH_OPERATION_TARGET: true,
    VIEW_USER_SETTING: false,
    VIEW_GOOGLE_REVIEW: false,
    EDIT_GOOGLE_REVIEW: false,
    READ_EDUCATION_REVIEW: false,
    EDIT_EDUCATION_REVIEW: false,
    EDIT_PT_LEVEL: false,
    READ_PT_LEVEL: false,
    EDIT_HIRE_TIME: false,
    VIEW_POINTS_BONUS: false,
    VIEW_RELOCATE_BONUS: false,
    EDIT_RELOCATE_BONUS: false,
  },
  [RoleType['櫃檯']]: {
    READ_HANDOVER: true,
    EDIT_COACH_OPERATION_TARGET: false,
    VIEW_USER_SETTING: false,
    VIEW_GOOGLE_REVIEW: false,
    EDIT_GOOGLE_REVIEW: false,
    READ_EDUCATION_REVIEW: false,
    EDIT_EDUCATION_REVIEW: false,
    EDIT_PT_LEVEL: false,
    READ_PT_LEVEL: false,
    EDIT_HIRE_TIME: false,
    VIEW_POINTS_BONUS: false,
    VIEW_RELOCATE_BONUS: false,
    EDIT_RELOCATE_BONUS: false,
  },
  [RoleType['教練組長']]: {
    READ_HANDOVER: false,
    EDIT_COACH_OPERATION_TARGET: true,
    VIEW_USER_SETTING: false,
    VIEW_GOOGLE_REVIEW: false,
    EDIT_GOOGLE_REVIEW: false,
    READ_EDUCATION_REVIEW: false,
    EDIT_EDUCATION_REVIEW: false,
    EDIT_PT_LEVEL: false,
    READ_PT_LEVEL: false,
    EDIT_HIRE_TIME: false,
    VIEW_POINTS_BONUS: true,
    VIEW_RELOCATE_BONUS: false,
    EDIT_RELOCATE_BONUS: false,
  },
  [RoleType['教練']]: {
    READ_HANDOVER: false,
    EDIT_COACH_OPERATION_TARGET: false,
    VIEW_USER_SETTING: false,
    VIEW_GOOGLE_REVIEW: false,
    EDIT_GOOGLE_REVIEW: false,
    READ_EDUCATION_REVIEW: false,
    EDIT_EDUCATION_REVIEW: false,
    EDIT_PT_LEVEL: false,
    READ_PT_LEVEL: false,
    EDIT_HIRE_TIME: false,
    VIEW_POINTS_BONUS: false,
    VIEW_RELOCATE_BONUS: false,
    EDIT_RELOCATE_BONUS: false,
  },
  [RoleType['物理治療師']]: {
    READ_HANDOVER: false,
    EDIT_COACH_OPERATION_TARGET: false,
    VIEW_USER_SETTING: false,
    VIEW_GOOGLE_REVIEW: true,
    EDIT_GOOGLE_REVIEW: false,
    READ_EDUCATION_REVIEW: true,
    EDIT_EDUCATION_REVIEW: false,
    EDIT_PT_LEVEL: false,
    READ_PT_LEVEL: false,
    EDIT_HIRE_TIME: false,
    VIEW_POINTS_BONUS: true,
    VIEW_RELOCATE_BONUS: true,
    EDIT_RELOCATE_BONUS: false,
  },
  [RoleType['物理治療師組長']]: {
    READ_HANDOVER: false,
    EDIT_COACH_OPERATION_TARGET: false,
    VIEW_USER_SETTING: false,
    VIEW_GOOGLE_REVIEW: true,
    EDIT_GOOGLE_REVIEW: true,
    READ_EDUCATION_REVIEW: true,
    EDIT_EDUCATION_REVIEW: true,
    EDIT_PT_LEVEL: false,
    READ_PT_LEVEL: false,
    EDIT_HIRE_TIME: false,
    VIEW_POINTS_BONUS: true,
    VIEW_RELOCATE_BONUS: true,
    EDIT_RELOCATE_BONUS: true,
  },
};
